language: node_js
node_js:
  - 12
git:
  depth: 3
cache: npm
notifications:
  email: false
script:
  - npm run lint
  - npm run test:coverage
after_success:
  - test -f ./coverage/lcov.info && npm run codecov
