language: node_js
node_js:
  - 12
git:
  depth: 3
cache:
  directories:
    - node_modules
    - "$(npm config get prefix)/bin"
    - "$(npm config get prefix)/lib/node_modules"
notifications:
  email: false
script:
  - npm run lint
  - npm run test:coverage
after_success:
  - test -f ./coverage/lcov.info && npm run codecov
